version: "3.8"

services:
  vllm:
    image: serve/vllm
    build:
      context: .
      dockerfile: Dockerfile.vllm
    command: --model $LLM_HF_REPO_ID $VLLM_ARGS
    environment:
      #- VLLM_API_KEY=${API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ${MODELS_CACHE_DIR:-"."}/${LLM_HF_REPO_ID}:/root/.cache/huggingface
    ipc: host
    expose:
      - 8000
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 60s
      timeout: 5s
      retries: 10

  tei:
    image: serve/tei
    build:
      context: .
      dockerfile: Dockerfile.tei
    command: --model-id $EMBEDDINGS_HF_REPO_ID $TEI_ARGS
    environment:
      #- API_KEY=${API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    volumes:
      - ${MODELS_CACHE_DIR:-"."}/${EMBEDDINGS_HF_REPO_ID}:/data
    expose:
      - 80
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 60s
      timeout: 5s
      retries: 10

  fastapi:
    image: serve/fastapi
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
      - 8000
    restart: always
    depends_on:
      vllm:
        condition: service_healthy
      tei:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 2s
      timeout: 5s
      retries: 10

  nginx:
    image: serve/nginx:1.25.0
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:8080
    depends_on:
      vllm:
        condition: service_healthy
      tei:
        condition: service_healthy
      fastapi:
        condition: service_healthy