[project]
name = "vLLMembeddings"
version = "1.0.0"
requires-python = ">=3.11"
license = { text = "MIT" }
dependencies = [
    "fastapi==0.110.0",
    "uvicorn[standard]==0.23.2",
    "openai==1.34.0",
    "requests==2.32.3",
]

[tool.ruff]
line-length = 100
